import { Printer, X } from 'lucide-react'
import type { Project, RubricCriterion, RubricDescriptor } from '../../types'
import { LEVELS } from '../../utils/levels'

// ─── Helpers ─────────────────────────────────────────────────────────────────

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December']
function fmtDate(iso: string) {
  const d = new Date(iso + 'T00:00:00')
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`
}

// ─── Styles ───────────────────────────────────────────────────────────────────
// Plain black-on-white text throughout — no colour, no badges/boxes, no point values.

const S: Record<string, React.CSSProperties> = {
  page:          { fontFamily: "'Georgia Pro', Georgia, serif", color: '#000', background: 'white', padding: '40px 48px' },
  title:         { fontSize: 22, fontWeight: 700, margin: 0 },
  subtitle:      { fontSize: 12, margin: '4px 0 0' },
  hr:            { border: 'none', borderTop: '1px solid #000', margin: '18px 0' },
  body:          {},
  critBlock:     { breakInside: 'avoid', marginBottom: 20 },
  critName:      { fontSize: 14, fontWeight: 700, margin: 0 },
  critMeta:      { fontSize: 11, margin: '2px 0 0' },
  critDesc:      { fontSize: 11, fontStyle: 'italic', margin: '4px 0 0' },
  grid:          { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginTop: 10, paddingTop: 8, borderTop: '1px solid #000' },
  levelLabel:    { fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em', margin: '0 0 2px' },
  levelMarks:    { fontSize: 9.5, margin: '0 0 4px' },
  levelText:     { fontSize: 10.5, lineHeight: 1.4, margin: 0 },
  footer:        { borderTop: '1px solid #000', paddingTop: 6, marginTop: 24, display: 'flex', justifyContent: 'space-between' },
  footerText:    { fontSize: 9, margin: 0 },
}

// ─── Rubric document ────────────────────────────────────────────────────────

interface DocProps {
  project: Project
  className: string
  criteria: RubricCriterion[]
  descriptors: RubricDescriptor[]
}

function RubricDocument({ project, className, criteria, descriptors }: DocProps) {
  const sorted = criteria.slice().sort((a, b) => a.sortIndex - b.sortIndex)

  const metaParts = [
    className,
    project.dueDate ? `Due ${fmtDate(project.dueDate)}` : null,
    `${project.totalMarks} marks`,
    project.semesterWeight > 0 ? `${Math.round(project.semesterWeight * 100)}% of semester` : null,
  ].filter(Boolean)

  return (
    <div className="print-report" style={S.page}>

      {/* Header */}
      <h1 style={S.title}>{project.name}</h1>
      <p style={S.subtitle}>Assessment Rubric · {metaParts.join(' · ')}</p>
      <hr style={S.hr} />

      {/* Criteria */}
      <div style={S.body}>
        {sorted.length === 0 && (
          <p style={{ fontSize: 12, textAlign: 'center', padding: '24px 0' }}>No criteria have been added to this rubric yet.</p>
        )}
        {sorted.map((c, i) => {
          const byLevel = descriptors.filter(d => d.criterionId === c.id)
          return (
            <div key={c.id} style={S.critBlock}>
              <p style={S.critName}>{i + 1}. {c.name || 'Untitled criterion'}</p>
              <p style={S.critMeta}>{c.maxMarks} marks · {Math.round(c.weight * 100)}% weight</p>
              {c.description && <p style={S.critDesc}>{c.description}</p>}

              <div style={S.grid}>
                {LEVELS.map(level => {
                  const d = byLevel.find(x => x.level === level.id)
                  const text = d?.text.trim()
                  const marks = Math.round((d?.score ?? level.defaultScore) * c.maxMarks)
                  return (
                    <div key={level.id}>
                      <p style={S.levelLabel}>{level.shortLabel}</p>
                      <p style={S.levelMarks}>{marks} marks</p>
                      <p style={S.levelText}>{text || 'No descriptor set'}</p>
                    </div>
                  )
                })}
              </div>
            </div>
          )
        })}
      </div>

      {/* Footer */}
      <div style={S.footer}>
        <p style={S.footerText}>Generated by WhipMarks</p>
        <p style={S.footerText}>{className} · {project.name}</p>
      </div>

    </div>
  )
}

// ─── Modal wrapper ────────────────────────────────────────────────────────────

interface Props extends DocProps {
  onClose: () => void
}

export function RubricExportModal({ onClose, ...docProps }: Props) {
  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-start justify-center overflow-y-auto py-8 px-4">
      <div className="w-full max-w-3xl" onClick={e => e.stopPropagation()}>

        <div className="print:hidden flex items-center justify-between mb-3">
          <div>
            <p className="text-sm font-semibold text-gray-100">{docProps.project.name}</p>
            <p className="text-xs text-gray-400">Rubric export preview</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 bg-gray-100 hover:bg-gray-100/80 text-gray-900 text-sm font-semibold px-4 py-2 rounded-lg transition-colors shadow-lg"
            >
              <Printer size={15} />
              Save as PDF
            </button>
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-100 rounded-lg hover:bg-gray-800 transition-colors"
            >
              <X size={16} />
            </button>
          </div>
        </div>

        <div className="rounded-xl overflow-hidden shadow-2xl">
          <RubricDocument {...docProps} />
        </div>

        <p className="print:hidden text-center text-xs text-gray-400/70 mt-3">
          "Save as PDF" → select Microsoft Print to PDF in the dialog
        </p>
      </div>
    </div>
  )
}
